create table blog_post (
  id bigint generated by default as identity primary key,
  title text,
  content text,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
 
);

INSERT INTO blog_post (title, content)
VALUES ('My First Blog Post', 'This is the content of my first blog post!');